### ISSUE TITLE
PDO v3 file description

### ISSUE THREAD

**Issue by PixnBits** [dpethes/pdo-tools-v2#2]
[pdo-tools v1](http://satd.sk/web/pdotools/) is able to handle PDO v3 files created by "Pepakura Designer 3" (and generates SVGs) wonderfully. (Thank you!)
Is it planned for v2 of pdo-tools to also handle this format? (If so, I'm assuming there will be a description file similar to [doc/pdo_v2_description.txt](https://github.com/dpethes/pdo-tools-v2/blob/3c45b42d023a53b923daa142f8b49edb27697814/doc/pdo_v2_description.txt)?)

**Comment by PixnBits** [comment]
I'd be glad to help translate code into a descriptor file, if desired. (but would need to see the relevant code :P) I've tried searching but the [two](http://forum.xentax.com/viewtopic.php?p=56980&sid=55d5f6482f3239571f0d61d5908b06fc#p56980) [descriptors](http://forum.xentax.com/viewtopic.php?p=107289&sid=47f516da96729e1705b0fdb64012126d#p107289) I've found seem incorrect, while pdo-tools v1 works great.

My particular interest in the v3 format comes as I'm trying to cut out some PDOs on a cricut machine (requires SVG) but the tabs are separate from the outline pieces. To remedy this I'm trying to either post-process the SVG output, or decipher the PDO format myself.

**Comment by dpethes** [comment]
The plan is to
- port obj, svg, pdf export from Pdo tools for the v3 format to support the v2 format
- publish the compression library used in exports in separate repository
- publish the ported exports in this repository
- merge v2 and v3 codebases
- publish the final result

The description of v3 is already done, it will be published in the last stage.

If I understand it correctly: you need the outline layer to take into account the tabs' outlines as well. That shouldn't be difficult to add. Please make a separate issue and attach a small sample of how it's exported now and how you would need it to be exported. I'll try to do port the svg export first and can work on it right after that.

**Comment by PixnBits** [comment]
separate issue created as #3 
thanks!!

**Comment by dpethes** [comment]
See https://github.com/dpethes/pdo-tools
