### ISSUE TITLE
New Feature: machine cutting (cricut)

### ISSUE THREAD

**Issue by PixnBits** [dpethes/pdo-tools-v2#3]
_(I'm using a [cube example from tamasoft](http://tamasoft.co.jp/pepakura-en/download/polygons/index.html))_

pdo-tools v1 is able to [export an SVG file](https://github.com/PixnBits/pdo-examples/blob/master/cricut/cube.svg) from [the PDO](https://github.com/PixnBits/pdo-examples/blob/master/cricut/cube.pdo) :+1: 

However, the tabs are separate from the outline. This poses an issue when using the SVG with paper cutting machines like a cricut as they will dutifully cut out the tabs separate from the outline. SVG editing is required to join the tabs to the outline and keep a crease line (here, [cube-cricut.svg](https://github.com/PixnBits/pdo-examples/blob/master/cricut/cube-cricut.svg)).

Could pdo-tools add an option to perform this processing, to support machine cutting?

Thanks so much!

**Comment by dpethes** [comment]
Do you want to test it? I have a windows build ready.

**Comment by PixnBits** [comment]
Exciting!
[Edit] I don't see it under [releases](https://github.com/dpethes/pdo-tools-v2/releases), should I run a build locally?

**Comment by dpethes** [comment]
No, try http://satd.sk/pages/pdotools/pdotools09m.zip (there's a new option in the Advanced tab)

**Comment by dpethes** [comment]
See https://github.com/dpethes/pdo-tools
