### ISSUE TITLE
packaging for arch linux

### ISSUE THREAD

**Issue by albfan** [dpethes/pdo-tools-v2#4]
Hi, I want to package pdotools for arch linux.

```
wget http://satd.sk/pages/pdotools/pdotools_l64gtk.zip
unzip pdotools_l64gtk.zip 
chmod +x pdotools
```

Checking `ldd pdotools` it requires libhpdf.2.2.1:

    sudo pacman -S libharu

Arch linux is now on 2.3.0 so:

    sudo ln -s /usr/lib/libhpdf-2.3.0.so /usr/lib/libhpdf-2.2.1.so

That works (but little bit hacky, can pdotools relay on libhpdf.so?).

Getting some pdo files: (A complex one)

    wget https://github.com/AchimPieters/Pepakura/blob/master/Iron%20Man%20-%20Helmet%20Mark%20VI/Iron%20Man%20-%20Helmet%20Mark%20VI%20.pdo

Trying to convert:

    ./pdotools Iron\ Man\ -\ Helmet\ Mark\ VI\ .pdo 

That doesn't work as pdotools doesn't work from command line, it shows a GUI (can we add command line only execution?).

GUI works as expected:

![pdotools  GUI](https://user-images.githubusercontent.com/220968/59842989-fbf3af80-9357-11e9-8504-de5f84e0747b.png)

![showing svg on inkscape](https://user-images.githubusercontent.com/220968/59842701-593b3100-9357-11e9-9a4f-947dc8cc1400.png)

Just wondering: 

- Will this repo allow to build pdotools from scratch? is it a different tool (v2)? a better tool?
- Can we add command line options? maybe ini config file `~/.pdotoolsrc`?

Right now I will package as said (doing the hack to find libhpdf) but will prefer to build from scratch

**Comment by dpethes** [comment]
Hi,
1. Relying on libhpdf.so should be possible, will look into it. I guess it will be 2.3.0 for most of people already, as it's a quite old version.
2. I actually have a command line version already, but as you're the first one asking for it, I never released it. It's a separate executable without dependencies on gtk/qt. Would that work for you?
3. This is actually a different tool than what's on the website. It's for the old PDO format used by Pepakura Designer 1, probably quite rare by now. 
I could probably release the source though.

**Comment by albfan** [comment]
All sounds great. 

1. Let me know if I can help, building or testing
2. I think so.
3. Release the source would be a nice idea. I can help with licenses if you want help on that. Maybe we can update this tool too.

Just let me know it there's any update

**Comment by albfan** [comment]
if you get any progress with any of this points let me know. I can help to cleanup and do a release

**Comment by albfan** [comment]
https://aur.archlinux.org/packages/pdo-tools-bin/

![Desktop file](https://user-images.githubusercontent.com/220968/81854855-cef74f00-955e-11ea-823b-7bbd242397c0.png)
