### ISSUE TITLE
Changes from 2018 release?

### ISSUE THREAD

**Issue by zackarychapple** [dpethes/pdo-tools-v2#5]
Hello!  Been using PDO tools for a couple days but went to look at the source here but it seems the updates from the 2018 release are not available.  Any chance they can get updated? 

https://satd.sk/pages/pdotools/

**Comment by dpethes** [comment]
This is actually a separate project for the older Pepakura format, that's not used anymore. I plan to release the sources for that one, but they need some preparation/cleanup first. Will likely happen later this year.

**Comment by zackarychapple** [comment]
That is fantastic, thank you for sharing.  There was some folks I was talking to about it and we're all excited to see and help.  I found a bug too would love to report so we can see about improving the tool.

**Comment by albfan** [comment]
Any chance to publish those old sources? I don't know even how to run this code project!

**Comment by dpethes** [comment]
Sources for PDO tools working with the Pepakura 2+ format are now published here https://github.com/dpethes/pdo-tools

**Comment by zackarychapple** [comment]
Thank you @dpethes !
